apiVersion: compute.cloud.com/v1
kind: EC2instance
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/managed-by: kustomize
  name: ec2instance-sample
spec:
  # TODO(user): Add fields here
